# There was no real reason to persist these in a database since user cannot add languages

languages = {}

languages = {
    "Plain Text": "misc",
    "Bash": "bsh",
    "C": "c",
    "C#": "csh",
    "C++": "cpp",
    "Clojure": "clj",
    "CoffeeScript": "coffee",
    "Common Lisp": "cl",
    "CSS": "css",
    "Emacs Lisp": "el",
    "F#": "fs",
    "Go": "go",
    "Haskell": "hs",
    "HTML": "html",
    "Java": "java",
    "JavaScript": "js",
    "Latex": "latex",
    "Lisp": "lisp",
    "Lua": "lua",
    "Nemerle": "n",
    "Objective C": "m",
    "OCAML": "ml",
    "Perl": "pl",
    "PHP": "php",
    "Protocol Buffers": "proto",
    "Python": "py",
    "Ruby": "rb",
    "Scala": "scala",
    "Scheme": "scm",
    "SQL": "sql",
    "Tex": "tex",
    "Visual Basic": "vb",
    "VHDL": "vhdl",
    "Wiki Text": "wiki",
    "XML": "xml",
    "XQuery": "xq",
    "XSLT": "xsl",
    "YAML": "yaml"
}
