messages = {}
messages['error'] = {
    400: "You have made a bad request",
    401: "You need to be authenticated to access this page",
    403: "You are not allowed to access this page",
    404: "Sorry. The page was not found",
    405: "Unsupported request method",
    500: "Oops. Something went wrong. Please try again later",
    'default': "Oops. Something went wrong. Please try again later"
}

languages = {}
languages = {
    "Plain Text": "misc",
    "Bash": "bsh",
    "C": "c",
    "C#": "csh",
    "C++": "cpp",
    "Clojure": "clj",
    "CoffeeScript": "coffee",
    "Common Lisp": "cl",
    "CSS": "css",
    "Emacs Lisp": "el",
    "F#": "fs",
    "Go": "go",
    "Haskell": "hs",
    "HTML": "html",
    "Java": "java",
    "JavaScript": "js",
    "Latex": "latex",
    "Lisp": "lisp",
    "Lua": "lua",
    "Nemerle": "n",
    "Objective C": "m",
    "OCAML": "ml",
    "Perl": "pl",
    "PHP": "php",
    "Protocol Buffers": "proto",
    "Python": "py",
    "Ruby": "rb",
    "Scala": "scala",
    "Scheme": "scm",
    "SQL": "sql",
    "Tex": "tex",
    "Visual Basic": "vb",
    "VHDL": "vhdl",
    "Wiki Text": "wiki",
    "XML": "xml",
    "XQuery": "xq",
    "XSLT": "xsl",
    "YAML": "yaml"
}
